apiVersion: v1
kind: ConfigMap
metadata:
  name: remote-app-config
data:
  nginxPort: {{.Values.pod.containerPort | quote}}
  hostName: localhost
  host: {{.Values.host.port | quote}}
  remoteName: {{.Values.remote.name}}
  remoteURI: {{.Values.remote.uri}}