# There is a more elegant way to do this - 
# https://serverfault.com/questions/577370/how-can-i-use-environment-variables-in-nginx-conf
apiVersion: v1
kind: ConfigMap
metadata:
  name: shell-nginx-config
data:
  nginx.conf: |
    worker_processes 1;
    events {
        worker_connections 1024;
    }
    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;
        server {
            listen {{.Values.pod.containerPort}};
            listen [::]:{{.Values.pod.containerPort}};
            server_name localhost;
            gzip                    on;
            gzip_comp_level         6;
            gzip_vary               on;
            gzip_min_length         1000;
            gzip_proxied            any;
            gzip_types              text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
            gzip_buffers            16 8k;
            client_max_body_size    256M;
            root /usr/share/nginx/html;
            index index.html;

            location /{{.Values.remote.name}} {
                proxy_pass http://{{.Values.remote.url}}:{{.Values.remote.port | quote}}/remoteEntry.json;
            }

            location /assets/ {
            autoindex on;
            }

            # Error handling
            error_page 500 502 503 504 /50x.html;
            location = /50x.html {
                root /usr/share/nginx/html;
            }
        }
    }